-- AI Schedule Assistant Database Schema
-- SQLite on MacBook

-- Schedules table
CREATE TABLE IF NOT EXISTS schedules (
  id TEXT PRIMARY KEY,               -- UUID
  device_id TEXT NOT NULL,           -- iPhone device identifier
  title TEXT NOT NULL,               -- Schedule title
  location TEXT,                      -- Location (optional)
  notes TEXT,                         -- Notes (optional)
  start_time INTEGER NOT NULL,        -- Unix timestamp (seconds), UTC
  end_time INTEGER,                   -- Unix timestamp (seconds), null means duration unknown
  reminder_time INTEGER,               -- Reminder time, Unix timestamp, UTC
  timezone TEXT DEFAULT 'Asia/Shanghai', -- Schedule timezone
  repeat_rule TEXT,                    -- Repeat rule (optional), format: FREQ=WEEKLY;BYDAY=MO
  is_completed INTEGER DEFAULT 0,    -- 0=incomplete, 1=completed
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_schedules_device ON schedules(device_id);
CREATE INDEX IF NOT EXISTS idx_schedules_time ON schedules(start_time);
CREATE INDEX IF NOT EXISTS idx_schedules_device_time ON schedules(device_id, start_time);

-- Sessions table
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,               -- UUID, generated by client
  device_id TEXT NOT NULL,          -- iPhone device identifier
  created_at INTEGER NOT NULL,       -- Unix timestamp (seconds)
  last_active_at INTEGER NOT NULL   -- Last active time
);

CREATE INDEX IF NOT EXISTS idx_sessions_device ON sessions(device_id);
CREATE INDEX IF NOT EXISTS idx_sessions_active ON sessions(last_active_at);
